// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT9jzs47L1WoCHQhCjNsb8Uwof9Y5YeLM',
    appId: '1:916994282675:web:4c0371c456e6935d6b0cc6',
    messagingSenderId: '916994282675',
    projectId: 'gymmy-saas',
    authDomain: 'gymmy-saas.firebaseapp.com',
    storageBucket: 'gymmy-saas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsKa9QzaFlZFh0SwRJjJFIXTpHIvrBynk',
    appId: '1:916994282675:android:d48512068cfdc3496b0cc6',
    messagingSenderId: '916994282675',
    projectId: 'gymmy-saas',
    storageBucket: 'gymmy-saas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm0r7gLk-AdSZ1UBKBNpVp1SpLbGYvrrc',
    appId: '1:916994282675:ios:61076377f25805656b0cc6',
    messagingSenderId: '916994282675',
    projectId: 'gymmy-saas',
    storageBucket: 'gymmy-saas.firebasestorage.app',
    iosBundleId: 'com.example.gymmy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm0r7gLk-AdSZ1UBKBNpVp1SpLbGYvrrc',
    appId: '1:916994282675:ios:61076377f25805656b0cc6',
    messagingSenderId: '916994282675',
    projectId: 'gymmy-saas',
    storageBucket: 'gymmy-saas.firebasestorage.app',
    iosBundleId: 'com.example.gymmy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT9jzs47L1WoCHQhCjNsb8Uwof9Y5YeLM',
    appId: '1:916994282675:web:9314070da2b4b4776b0cc6',
    messagingSenderId: '916994282675',
    projectId: 'gymmy-saas',
    authDomain: 'gymmy-saas.firebaseapp.com',
    storageBucket: 'gymmy-saas.firebasestorage.app',
  );
}
